---
- name: single handler
  hosts: n01605112-c-vm-1.canadaeast.cloudapp.azure.com
  tasks:
    - name: Install Apache web server
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: Add hostname to index.html file
      ansible.builtin.lineinfile:
        path: /var/www/html/index.html
        line: "Hi this is Shraddha from Security lab in Horia's lecture with Hostname: {{ ansible_hostname }}"
        create: yes
      notify: restart apache

    - name: Enable Apache service to auto-start on system reboots
      ansible.builtin.service:
        name: httpd
        enabled: yes

    - name: Start Apache service
      ansible.builtin.service:
        name: httpd
        state: started

  handlers:
    - name: restart apache
      ansible.builtin.service:
        name: httpd
        state: restarted
